### PR TITLE
Create DeterminantandTrace.R

### PR DESCRIPTION
**Pull request by jeksterslab**
Let me know if there is anything else I can help you with regarding these methods.

### CODE REVIEW

**Comment by mikldk** [comment]
Thanks, @jeksterslab for this contribution. Can you please implement the functions using `y_fn()`, i.e. `y_fn(x, "Trace")` etc.? Also please add the generic `tr`/`det` with a `UseMethod()`. See e.g. how `diag()` was implemented.

**Comment by jeksterslab** [comment]
Here you go @mikldk. I hope what I did is appropriate.

**Comment by mikldk** [comment]
Thanks, @jeksterslab -- can you please rename the file to `linalg.R`?

**Comment by jeksterslab** [comment]
Done @mikldk. Btw I am willing to generate more methods for yacas commands that people would like to be included in Ryacas.

**Comment by mikldk** [comment]
Thanks, @jeksterslab . This now look fine. Can I have you write a few tests for the new methods as well? :smile:

**Comment by jeksterslab** [comment]
By tests, you mean something like below? Do you want me to put the tests on the testthat folder?

# Numerical Example
A <- mtcars[, c(1,3,4,5,6,7)]
Sigma <- cov(A)
ex1.default <- det(Sigma)
ex1.yac_symbol <- det(ysym(Sigma)) %>% y_fn("N", "10")
ex1.yac_symbol <- as.numeric(ex1.yac_symbol$yacas_cmd)
test_that("3678523", {
  expect_equal(
    ex1.default,
    ex1.yac_symbol
  )
})
# Symbolic Example
B <- matrix(
    c("a", "c", "b", "d"),
    ncol = 2
  )
ex2.yac_symbol <- det(ysym(B))
test_that("a*d-b*c", {
  expect_equal(
    "a*d-b*c",
    ex2.yac_symbol$yacas_cmd
  )
})

**Comment by mikldk** [comment]
Yes, something like that. Yes, maybe in a new file, `test-linalg.R` following the same template as the other tests. And also tests triggering the errors, please.

**Comment by jeksterslab** [comment]
Sure. I'll study the existing tests first before pushing the quick tests I wrote.

**Comment by jeksterslab** [comment]
I was having issues with `det` in `Ryacas` so I decided to take a look at `yacas`. I am getting inconsistent results.

```
// SYMBOLIC

A := {{a, b, c}, {d, e, f}, {g, h, i}};
Determinant(A);

// Returns 3*a*e-a*f*h+c*d*h-3*b*d+b*f*g-c*e*g on my machine.
// Based on Wikipedia (https://en.wikipedia.org/wiki/Determinant) it should return
// a*e*i + b*f*g + c*d*h - c*e*g - b*d*i - a*f*h.


// NUMERIC

B := {{1, 0.50, 0.25}, {0.50, 1, 0.75}, {0.25, 0.75, 1}};
N(Determinant(B));

// Returns 0.3125 on my machine.


// TESTING RESULT OF SYMBOLIC

a := 1;
b := 0.50;
c := 0.25;
d := 0.50;
e := 1;
f := 0.75;
g := 0.25;
h := 0.75;
i := 1;
C := {{a, b, c}, {d, e, f}, {g, h, i}};

// `N(Determinant(C))` returns 0.3125 which is the same as the numeric example
// but not the same as the symbolic example.


// USING SYMBOLIC RESULT WITH NUMBER

3*a*e - a*f*h + c*d*h - 3*b*d + b*f*g - c*e*g;

// Returns 1.8125 which is not equal to 0.3125

```

**Comment by jeksterslab** [comment]
Using a different set of symbols `x1` to `x9` works. Hmmm...

```
// SYMBOLIC

A := {{x1, x2, x3}, {x4, x5, x6}, {x7, x8, x9}};
Determinant(A);

// NUMERIC

B := {{1, 0.50, 0.25}, {0.50, 1, 0.75}, {0.25, 0.75, 1}};
N(Determinant(B));

// TESTING RESULT OF SYMBOLIC

x1 := 1;
x2 := 0.50;
x3 := 0.25;
x4 := 0.50;
x5 := 1;
x6 := 0.75;
x7 := 0.25;
x8 := 0.75;
x9 := 1;
C := {{x1, x2, x3}, {x4, x5, x6}, {x7, x8, x9}};

N(Determinant(A));
N(Determinant(B));
N(Determinant(C));
N(x1*x5*x9-x1*x6*x8+x3*x4*x8-x2*x4*x9+x2*x6*x7-x3*x5*x7);
```

**Comment by mikldk** [comment]
@grzegorzmazur - do you know what is wrong with [the example above](https://github.com/r-cas/ryacas/pull/55#issuecomment-772489559)?

Thanks, @jeksterslab. Can you maybe add a few `expect_error()`'s?

**Comment by jeksterslab** [comment]
Added test coverage for errors.

**Comment by jeksterslab** [comment]
Regarding the `yacas` error, since the problems are with `a*e*i` resulting in `3*a*e` and `b*d*i` resulting in `3*b*d`, my hunch is that `i` is interpreted as something other than a variable. Maybe an imaginary unit? I don't know enough Mathematics to know for sure. :-)

**Comment by grzegorzmazur** [comment]
Hi,

Sorry for being so late to the party. I've fixed a silly problem with local symbols leaking in Determinant(), please have a look at https://github.com/grzegorzmazur/yacas/commit/093a44ffb7b8529bee1e65fb1361a44809c724ab

 Sorry for the problem,
Grzesiek

**Comment by mikldk** [comment]
Thanks, @jeksterslab , for also catching the bug in yacas; and thanks to @grzegorzmazur for fixing that :smile:.

**Comment by jeksterslab** [comment]
Thanks @grzegorzmazur for `yacas` and @mikldk for `Ryacas`. By the way I am willing to continue working on creating methods that others might find useful. I started with `det` and `tr` only because I needed them.

**Comment by mikldk** [comment]
Thanks, @jeksterslab . You are more than welcome to submit more PR's :1st_place_medal: :+1:

**Pull request merged**
